# Generated by Django 5.0.6 on 2024-05-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VisitCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(max_length=255)),
                ("happen_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RunSQL(
            """
            INSERT INTO d3js_visitcount (ip_address, happen_time) VALUES 
            ('192.168.1.1', '2024-05-22 10:15:00'),
            ('192.168.1.2', '2024-05-22 11:20:00'),
            ('192.168.1.3', '2024-05-23 12:25:00'),
            ('192.168.1.4', '2024-05-23 13:30:00'),
            ('192.168.1.5', '2024-05-23 14:35:00'),
            ('192.168.1.6', '2024-05-24 15:40:00'),
            ('192.168.1.7', '2024-05-24 16:45:00');
            """
        ),
    ]
